CREATE TABLE [dbo].[SeminarSessions]
(
	[Id] VARCHAR(250) NOT NULL PRIMARY KEY,
	[SeminarId] VARCHAR(250) NOT NULL,
	[Status] VARCHAR(50) NOT NULL,
	[StartTime] DATETIME NULL,
	[EndTime] DATETIME NULL,
	FOREIGN KEY (SeminarId) REFERENCES Seminars(Id)
)
